version: "3"
services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 50070:50070
    env_file:
      - ./config/namenode.env
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - hadoop-resource:/opt/hadoop/etc/hadoop
    networks:
      - hadoop_network

  datanode:
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    env_file:
      - ./config/datanode.env
    networks:
      - hadoop_network

  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config/namenode.env
    volumes:
      - ./test.sh:/opt/test.sh
    networks:
      - hadoop_network

  nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config/namenode.env
    networks:
      - hadoop_network

volumes:
  hadoop-resource:

networks:
  hadoop_network:
    name: hadoop_network
